### ISSUE TITLE
Add Jerry cluster to configured clusters

### ISSUE THREAD

**Issue by SamoKopecky** [operate-first/service-catalog#113]
### Additional context

The Jerry cluster hasn't been added to the list of configured clusters.

### Acceptance Criteria

- [x] Add [this](https://github.com/operate-first/apps/blob/master/cluster-scope/bundles/service-catalog-k8s-plugin/kustomization.yaml) bundle to the Jerry overlay in apps repo (no need to add since jerry includes the `common` overlay)
- [x] Create a ConfigMap for the cluster name and environment (https://github.com/operate-first/apps/pull/2504)
- [x] Create a role for jerry auth method in vault
- [x] Update `app-config.prod.yaml` (https://github.com/operate-first/service-catalog/pull/116)

**Comment by SamoKopecky** [comment]
Currenly not working because of this issue: https://github.com/operate-first/apps/issues/2508

**Comment by tumido** [comment]
This is resolved now :slightly_smiling_face:
