### ISSUE TITLE
Plugin: Install and configure Kubernetes plugin

### ISSUE THREAD

**Issue by tumido** [operate-first/service-catalog#12]
https://backstage.io/docs/features/kubernetes/overview

Provide public overview of publicly available namespaces on all Operate First clusters

**Comment by tumido** [comment]
Kubernetes plugin to backstage offers 2 views:

1. On component level show related resources in kube clusters (like a OCP console with view permissions for pods only)
2. On top level show cluster status (like ACM cluster list overview)

Ideally we should offer both for transparency, I think 2) has more priority, since it can replace https://www.operate-first.cloud/community-cloud "Clusters" section

**Comment by SamoKopecky** [comment]
/close
Fix is now deployed in the live version and can be verified by visting:
https://service-catalog.operate-first.cloud/catalog/default/component/Peribolos-as-a-service/kubernetes
