### ISSUE TITLE
Describe ACM

### ISSUE THREAD

**Issue by SamoKopecky** [operate-first/service-catalog#143]
### Additional context

Describe the operate first project `ACM` in service catalog using backstage entities.

### Acceptance Criteria

- [ ] Create a system in backstage

**Comment by SamoKopecky** [comment]
I think this Issue can be closed since we have https://service-catalog.operate-first.cloud/catalog/default/system/acm.
WDYT @tumido ?

**Comment by tumido** [comment]
Resolved via https://github.com/operate-first/apps/pull/2686
