### ISSUE TITLE
Provision a new web terminal instance for user and link to it

### ISSUE THREAD

**Issue by tumido** [operate-first/service-catalog#151]
Depends on #150 

### Additional context

Similarly to Web Terminal in OpenShift, provision a single button click access to web terminal

### Acceptance Criteria

- [ ] Replicate openshift console bindings into web terminal operator
- [ ] Display a trigger button on Cluster resource page
- [ ] Display a link to a running terminal 

### Relevant links

https://github.com/openshift/console/tree/master/frontend/packages/console-app/src/components/cloud-shell
https://github.com/redhat-developer/web-terminal-operator

**Comment by mimotej** [comment]
This issue has been resolved by creating a component that works inside a backstage (as #152 wants) 
Example provided here:
![image](https://user-images.githubusercontent.com/47832967/233916452-f1246948-a0b0-4dcc-baef-d51541705dfc.png)
