### ISSUE TITLE
Display interactive web terminal of front end

### ISSUE THREAD

**Issue by tumido** [operate-first/service-catalog#152]
### Additional context

Similarly to OCP web terminal - provide interactive display for web terminal

### Acceptance Criteria

- [ ] Instead of pointing user to a url for web terminal, make it so that it has it's own UI in backstage

### Relevant links

Enhancement of #151

**Comment by mimotej** [comment]
This issue has been resolved final component looks like this:
![image](https://user-images.githubusercontent.com/47832967/233916619-96bb05be-0bda-47f6-b82e-65ff5048fada.png)

Some of the related PRs:
https://github.com/operate-first/service-catalog/pull/190
https://github.com/operate-first/service-catalog/pull/193
https://github.com/operate-first/service-catalog/pull/206
https://github.com/janus-idp/webterminal-proxy/pull/1
https://github.com/janus-idp/webterminal-proxy/pull/7
