### ISSUE TITLE
Spike: A single component of Operate First is defined

### ISSUE THREAD

**Issue by tumido** [operate-first/service-catalog#25]
The idea is to pick any of Operate First services and fully flesh it out as a component - providing all possible options and showing all easily available Backstage functions so we can demo the real power of Backstage.

**Comment by tumido** [comment]
I think there are 2 possible candidates for this entry:

- Peribolos as a service
- Service catalog itself

Feel free to choose

**Comment by SamoKopecky** [comment]
I think `Peribolos as a service` would be the best choice, since its a more mature service.

**Comment by SamoKopecky** [comment]
I think when `k8s` and `techdocs` plugins are installed we can them to the `peribolos as a service` service and close this issue.

**Comment by tumido** [comment]
Resolved
