### ISSUE TITLE
Service catalog fails to connect to DB, DB seems full

### ISSUE THREAD

**Issue by tumido** [operate-first/service-catalog#48]
DB instance is reporting

https://console-openshift-console.apps.smaug.na.operate-first.cloud/k8s/ns/service-catalog/pods/service-catalog-instance1-rnqr-0/logs

```
2022-07-18 07:26:18,834 INFO: Lock owner: None; I am service-catalog-instance1-rnqr-0
2022-07-18 07:26:18,835 INFO: starting as a secondary
2022-07-18 07:26:19.618 UTC [2655024] FATAL:  could not write lock file "postmaster.pid": No space left on device
2022-07-18 07:26:19,627 INFO: postmaster pid=2655024
```

And backstage can't connect to the DB:

https://console-openshift-console.apps.smaug.na.operate-first.cloud/k8s/ns/service-catalog/pods/service-catalog-78d66589db-jfm28/logs

```
Backend failed to start up, Error: Failed to connect to the database to make sure that 'backstage_plugin_catalog' exists, KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
```

DB PVCs really seems full, however this feel a bit excessive data compared to our catalog size.

![image](https://user-images.githubusercontent.com/7453394/179463086-5004bd46-3fa5-49d3-9984-ca01d9464252.png)

Please investigate. I think we should just drop the database - re-create the PG cluster.

**Comment by SamoKopecky** [comment]
I did some digging around on my development setup and I think the table `static_assets_cache` might be getting the reason why the storage volumes got consumed so fast. 
I am going to recreate the PG cluster, and I will carefully watch the volumes just to make sure that its really the `static_assets_cache` that is getting too big.

**Comment by SamoKopecky** [comment]
It turns out the issue was actually in the backups, they were being preserved indefinitely and so the volume got used up. Creating PR to fix this.

**Comment by SamoKopecky** [comment]
The change can be verified by viewing the deployed manifest file here:
https://console-openshift-console.apps.smaug.na.operate-first.cloud/k8s/ns/service-catalog/postgres-operator.crunchydata.com~v1beta1~PostgresCluster/service-catalog/yaml

Changes are added to:
- `.spec.backups.pgbackrest.global`
- `.spec.backups.pgbackrest.[0].schedules`

This should prevent the PV from being used up in a short time.
