### ISSUE TITLE
Bug: Home screen icons are stretched

### ISSUE THREAD

**Issue by tumido** [operate-first/service-catalog#52]
CSS for `<img />` on home screen doesn't include `object-fit: contain` making icons stretched:

Now:
![image](https://user-images.githubusercontent.com/7453394/179701418-c2a1779b-16df-4f03-9eb4-78d9b4388905.png)

Desired:
![image](https://user-images.githubusercontent.com/7453394/179701352-0703e139-82e0-4638-be65-f0919bda8d23.png)

**Comment by schwesig** [comment]
it is this link?
https://service-catalog.operate-first.cloud/
Then there is still a stretched problem (at least with OpenDataHub)
Screenshot 2022-08-02 10-57 ET, Chrome


![Image](https://user-images.githubusercontent.com/89909507/182406216-b8a453bf-f89f-4981-9d33-b70526220c72.png)

**Comment by schwesig** [comment]
-1

**Comment by SamoKopecky** [comment]
Its because we still haven't created a new release and the service catalog is still running on the old image.

**Comment by SamoKopecky** [comment]
/close
Fix is now deployed in the live version and can be verified by visting:
https://service-catalog.operate-first.cloud/
