### ISSUE TITLE
Display component icon on service detail page

### ISSUE THREAD

**Issue by tumido** [operate-first/service-catalog#53]
Show logo icon in component details page - either in masthead or on the About card.

![image](https://user-images.githubusercontent.com/7453394/179701892-fed5b73d-8ee2-4c08-976d-e9b676d32020.png)

**Comment by SamoKopecky** [comment]
I came up with two variants:

1. Icon under the about title:

![image](https://user-images.githubusercontent.com/44006847/183413741-164abeed-e58d-4d28-b830-49e51cee74ab.png)


2. Icon near the description:

![image](https://user-images.githubusercontent.com/44006847/183413716-61702be1-340e-4fce-afe9-70e84021168a.png)

Let me know which one you think is better.
/assign

**Comment by tumido** [comment]
Sorry, I don't like either. What about we put it into the masthead? Like.. left of the `"ArgoCD"` title on the top?
