### ISSUE TITLE
Bug: Refresh button on Component details page results in permission error

### ISSUE THREAD

**Issue by tumido** [operate-first/service-catalog#54]
Clicking the refresh button results in following error:

- [x] fix
- [x] deploy in a new release

![image](https://user-images.githubusercontent.com/7453394/179702142-9c86b0a8-e0cb-453e-8808-2f00d321c348.png)

**Comment by schwesig** [comment]
Not yet a new release
back to progress

**Comment by SamoKopecky** [comment]
/close
Fix is now deployed in the live version and can be verified by visting:
https://service-catalog.operate-first.cloud/
