### ISSUE TITLE
Tidy up layout of cards for all entities and add plugins to other entity types

### ISSUE THREAD

**Issue by SamoKopecky** [operate-first/service-catalog#77]
The layout of cards for entities is usable but it could be a lot better, for example:
- The entity home page has big gaps if configuration for some plugins is missing, maybe we can solve this by putting each plugin on its own row and stop putting more then one plugin on one row
- Investigate whether navigation items like `Docs` can be hidden if the docs annotation is missing in the entity configuration file
- Investigate if this card can be hidden if there are no sub-components

![image](https://user-images.githubusercontent.com/44006847/182158556-cbb8c031-d3b8-4edb-bbe9-aba82e2636ed.png)

Entities other then `Component` with `kind: service` are missing cards for plugins:
- `domain` entity is missing cards for ADR, TechDocs plugins
- `component` with the type `website` is also missing some plugins like ADRs and k8s
- `component` with the type `library` is using the default entity page which is missing a lot of cards
- Investigate whether any other entities are missing some plugins that make sense to show

**Comment by tumido** [comment]
Resolved via #119
